//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.2.2-SNAPSHOT
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from E:\Projects\C#\LTSASharp\LTSASharp\Parsing\FSPActual.g4 by ANTLR 4.2.2-SNAPSHOT

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

namespace LTSASharp.Parsing {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="FSPActualParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.2.2-SNAPSHOT")]
[System.CLSCompliant(false)]
public interface IFSPActualVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.relabelDefs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelabelDefs([NotNull] FSPActualParser.RelabelDefsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] FSPActualParser.ExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.compositeDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompositeDef([NotNull] FSPActualParser.CompositeDefContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.actionPrefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActionPrefix([NotNull] FSPActualParser.ActionPrefixContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.bitOrExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitOrExpr([NotNull] FSPActualParser.BitOrExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.ranges"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRanges([NotNull] FSPActualParser.RangesContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.fltl_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFltl_or([NotNull] FSPActualParser.Fltl_orContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.localProcess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocalProcess([NotNull] FSPActualParser.LocalProcessContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.seqProcessList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSeqProcessList([NotNull] FSPActualParser.SeqProcessListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.priority"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPriority([NotNull] FSPActualParser.PriorityContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.sequentialComposition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSequentialComposition([NotNull] FSPActualParser.SequentialCompositionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterList([NotNull] FSPActualParser.ParameterListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.rangeDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRangeDef([NotNull] FSPActualParser.RangeDefContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.fltl_base"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFltl_base([NotNull] FSPActualParser.Fltl_baseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.menuDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMenuDef([NotNull] FSPActualParser.MenuDefContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.equalityExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqualityExpr([NotNull] FSPActualParser.EqualityExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.prefixLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrefixLabel([NotNull] FSPActualParser.PrefixLabelContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.actionLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActionLabel([NotNull] FSPActualParser.ActionLabelContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.assertDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssertDef([NotNull] FSPActualParser.AssertDefContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument([NotNull] FSPActualParser.ArgumentContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.propertyDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertyDef([NotNull] FSPActualParser.PropertyDefContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.fltl_binary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFltl_binary([NotNull] FSPActualParser.Fltl_binaryContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.bitAndExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitAndExpr([NotNull] FSPActualParser.BitAndExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.setDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSetDef([NotNull] FSPActualParser.SetDefContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.actionLabelTail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActionLabelTail([NotNull] FSPActualParser.ActionLabelTailContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.fltl_and"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFltl_and([NotNull] FSPActualParser.Fltl_andContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.orExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrExpr([NotNull] FSPActualParser.OrExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.baseLocalProcess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseLocalProcess([NotNull] FSPActualParser.BaseLocalProcessContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.alphabetExtension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlphabetExtension([NotNull] FSPActualParser.AlphabetExtensionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.hiding"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHiding([NotNull] FSPActualParser.HidingContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.relabelDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelabelDef([NotNull] FSPActualParser.RelabelDefContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.indices"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndices([NotNull] FSPActualParser.IndicesContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.parallelComposition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParallelComposition([NotNull] FSPActualParser.ParallelCompositionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.simpleExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleExpression([NotNull] FSPActualParser.SimpleExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.localProcessDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocalProcessDef([NotNull] FSPActualParser.LocalProcessDefContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.andExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndExpr([NotNull] FSPActualParser.AndExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRange([NotNull] FSPActualParser.RangeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.choice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChoice([NotNull] FSPActualParser.ChoiceContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParam([NotNull] FSPActualParser.ParamContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSet([NotNull] FSPActualParser.SetContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.relabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelabel([NotNull] FSPActualParser.RelabelContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.fsp_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFsp_definition([NotNull] FSPActualParser.Fsp_definitionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.setElements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSetElements([NotNull] FSPActualParser.SetElementsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.initially"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitially([NotNull] FSPActualParser.InitiallyContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.localProcessDefs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocalProcessDefs([NotNull] FSPActualParser.LocalProcessDefsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.fltl_unary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFltl_unary([NotNull] FSPActualParser.Fltl_unaryContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.compositeBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompositeBody([NotNull] FSPActualParser.CompositeBodyContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter([NotNull] FSPActualParser.ParameterContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.guard"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGuard([NotNull] FSPActualParser.GuardContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.baseExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseExpr([NotNull] FSPActualParser.BaseExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.fluentDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFluentDef([NotNull] FSPActualParser.FluentDefContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.processBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcessBody([NotNull] FSPActualParser.ProcessBodyContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.constantDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstantDef([NotNull] FSPActualParser.ConstantDefContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.indexRanges"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexRanges([NotNull] FSPActualParser.IndexRangesContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.fsp_description"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFsp_description([NotNull] FSPActualParser.Fsp_descriptionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.processRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcessRef([NotNull] FSPActualParser.ProcessRefContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.actionRange"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActionRange([NotNull] FSPActualParser.ActionRangeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.shiftExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShiftExpr([NotNull] FSPActualParser.ShiftExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.multiplicativeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicativeExpr([NotNull] FSPActualParser.MultiplicativeExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.additiveExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditiveExpr([NotNull] FSPActualParser.AdditiveExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgumentList([NotNull] FSPActualParser.ArgumentListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.actionLabelsTail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActionLabelsTail([NotNull] FSPActualParser.ActionLabelsTailContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.unaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpr([NotNull] FSPActualParser.UnaryExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.relationalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationalExpr([NotNull] FSPActualParser.RelationalExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.progressDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgressDef([NotNull] FSPActualParser.ProgressDefContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.actionLabels"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActionLabels([NotNull] FSPActualParser.ActionLabelsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.bitExclOrExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitExclOrExpr([NotNull] FSPActualParser.BitExclOrExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="FSPActualParser.processDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcessDef([NotNull] FSPActualParser.ProcessDefContext context);
}
} // namespace LTSASharp.Parsing
