//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.2.2-SNAPSHOT
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from E:\Projects\C#\LTSASharp\LTSASharp\Parsing\FSPActual.g4 by ANTLR 4.2.2-SNAPSHOT

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

namespace LTSASharp.Parsing {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IFSPActualListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.2.2-SNAPSHOT")]
[System.CLSCompliant(false)]
public partial class FSPActualBaseListener : IFSPActualListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.relabelDefs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelabelDefs([NotNull] FSPActualParser.RelabelDefsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.relabelDefs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelabelDefs([NotNull] FSPActualParser.RelabelDefsContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] FSPActualParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] FSPActualParser.ExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.compositeDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompositeDef([NotNull] FSPActualParser.CompositeDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.compositeDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompositeDef([NotNull] FSPActualParser.CompositeDefContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.actionPrefix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActionPrefix([NotNull] FSPActualParser.ActionPrefixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.actionPrefix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActionPrefix([NotNull] FSPActualParser.ActionPrefixContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.bitOrExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBitOrExpr([NotNull] FSPActualParser.BitOrExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.bitOrExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBitOrExpr([NotNull] FSPActualParser.BitOrExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.ranges"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRanges([NotNull] FSPActualParser.RangesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.ranges"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRanges([NotNull] FSPActualParser.RangesContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.fltl_or"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFltl_or([NotNull] FSPActualParser.Fltl_orContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.fltl_or"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFltl_or([NotNull] FSPActualParser.Fltl_orContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.localProcess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocalProcess([NotNull] FSPActualParser.LocalProcessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.localProcess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocalProcess([NotNull] FSPActualParser.LocalProcessContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.seqProcessList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSeqProcessList([NotNull] FSPActualParser.SeqProcessListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.seqProcessList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSeqProcessList([NotNull] FSPActualParser.SeqProcessListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.priority"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPriority([NotNull] FSPActualParser.PriorityContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.priority"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPriority([NotNull] FSPActualParser.PriorityContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.sequentialComposition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSequentialComposition([NotNull] FSPActualParser.SequentialCompositionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.sequentialComposition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSequentialComposition([NotNull] FSPActualParser.SequentialCompositionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterList([NotNull] FSPActualParser.ParameterListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterList([NotNull] FSPActualParser.ParameterListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.rangeDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRangeDef([NotNull] FSPActualParser.RangeDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.rangeDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRangeDef([NotNull] FSPActualParser.RangeDefContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.fltl_base"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFltl_base([NotNull] FSPActualParser.Fltl_baseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.fltl_base"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFltl_base([NotNull] FSPActualParser.Fltl_baseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.menuDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMenuDef([NotNull] FSPActualParser.MenuDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.menuDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMenuDef([NotNull] FSPActualParser.MenuDefContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.equalityExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEqualityExpr([NotNull] FSPActualParser.EqualityExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.equalityExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEqualityExpr([NotNull] FSPActualParser.EqualityExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.prefixLabel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrefixLabel([NotNull] FSPActualParser.PrefixLabelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.prefixLabel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrefixLabel([NotNull] FSPActualParser.PrefixLabelContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.actionLabel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActionLabel([NotNull] FSPActualParser.ActionLabelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.actionLabel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActionLabel([NotNull] FSPActualParser.ActionLabelContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.assertDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssertDef([NotNull] FSPActualParser.AssertDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.assertDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssertDef([NotNull] FSPActualParser.AssertDefContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgument([NotNull] FSPActualParser.ArgumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgument([NotNull] FSPActualParser.ArgumentContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.propertyDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertyDef([NotNull] FSPActualParser.PropertyDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.propertyDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertyDef([NotNull] FSPActualParser.PropertyDefContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.fltl_binary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFltl_binary([NotNull] FSPActualParser.Fltl_binaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.fltl_binary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFltl_binary([NotNull] FSPActualParser.Fltl_binaryContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.bitAndExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBitAndExpr([NotNull] FSPActualParser.BitAndExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.bitAndExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBitAndExpr([NotNull] FSPActualParser.BitAndExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.setDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetDef([NotNull] FSPActualParser.SetDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.setDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetDef([NotNull] FSPActualParser.SetDefContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.actionLabelTail"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActionLabelTail([NotNull] FSPActualParser.ActionLabelTailContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.actionLabelTail"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActionLabelTail([NotNull] FSPActualParser.ActionLabelTailContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.fltl_and"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFltl_and([NotNull] FSPActualParser.Fltl_andContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.fltl_and"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFltl_and([NotNull] FSPActualParser.Fltl_andContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.orExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrExpr([NotNull] FSPActualParser.OrExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.orExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrExpr([NotNull] FSPActualParser.OrExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.baseLocalProcess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBaseLocalProcess([NotNull] FSPActualParser.BaseLocalProcessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.baseLocalProcess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBaseLocalProcess([NotNull] FSPActualParser.BaseLocalProcessContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.alphabetExtension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAlphabetExtension([NotNull] FSPActualParser.AlphabetExtensionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.alphabetExtension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAlphabetExtension([NotNull] FSPActualParser.AlphabetExtensionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.hiding"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHiding([NotNull] FSPActualParser.HidingContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.hiding"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHiding([NotNull] FSPActualParser.HidingContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.relabelDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelabelDef([NotNull] FSPActualParser.RelabelDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.relabelDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelabelDef([NotNull] FSPActualParser.RelabelDefContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.indices"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndices([NotNull] FSPActualParser.IndicesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.indices"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndices([NotNull] FSPActualParser.IndicesContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.parallelComposition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParallelComposition([NotNull] FSPActualParser.ParallelCompositionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.parallelComposition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParallelComposition([NotNull] FSPActualParser.ParallelCompositionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.simpleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleExpression([NotNull] FSPActualParser.SimpleExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.simpleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleExpression([NotNull] FSPActualParser.SimpleExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.localProcessDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocalProcessDef([NotNull] FSPActualParser.LocalProcessDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.localProcessDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocalProcessDef([NotNull] FSPActualParser.LocalProcessDefContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.andExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAndExpr([NotNull] FSPActualParser.AndExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.andExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAndExpr([NotNull] FSPActualParser.AndExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.range"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRange([NotNull] FSPActualParser.RangeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.range"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRange([NotNull] FSPActualParser.RangeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.choice"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChoice([NotNull] FSPActualParser.ChoiceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.choice"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChoice([NotNull] FSPActualParser.ChoiceContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParam([NotNull] FSPActualParser.ParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParam([NotNull] FSPActualParser.ParamContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.set"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSet([NotNull] FSPActualParser.SetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.set"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSet([NotNull] FSPActualParser.SetContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.relabel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelabel([NotNull] FSPActualParser.RelabelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.relabel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelabel([NotNull] FSPActualParser.RelabelContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.fsp_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFsp_definition([NotNull] FSPActualParser.Fsp_definitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.fsp_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFsp_definition([NotNull] FSPActualParser.Fsp_definitionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.setElements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetElements([NotNull] FSPActualParser.SetElementsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.setElements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetElements([NotNull] FSPActualParser.SetElementsContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.initially"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitially([NotNull] FSPActualParser.InitiallyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.initially"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitially([NotNull] FSPActualParser.InitiallyContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.localProcessDefs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocalProcessDefs([NotNull] FSPActualParser.LocalProcessDefsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.localProcessDefs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocalProcessDefs([NotNull] FSPActualParser.LocalProcessDefsContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.fltl_unary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFltl_unary([NotNull] FSPActualParser.Fltl_unaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.fltl_unary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFltl_unary([NotNull] FSPActualParser.Fltl_unaryContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.compositeBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompositeBody([NotNull] FSPActualParser.CompositeBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.compositeBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompositeBody([NotNull] FSPActualParser.CompositeBodyContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter([NotNull] FSPActualParser.ParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter([NotNull] FSPActualParser.ParameterContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.guard"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGuard([NotNull] FSPActualParser.GuardContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.guard"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGuard([NotNull] FSPActualParser.GuardContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.baseExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBaseExpr([NotNull] FSPActualParser.BaseExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.baseExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBaseExpr([NotNull] FSPActualParser.BaseExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.fluentDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFluentDef([NotNull] FSPActualParser.FluentDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.fluentDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFluentDef([NotNull] FSPActualParser.FluentDefContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.processBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProcessBody([NotNull] FSPActualParser.ProcessBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.processBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProcessBody([NotNull] FSPActualParser.ProcessBodyContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.constantDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstantDef([NotNull] FSPActualParser.ConstantDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.constantDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstantDef([NotNull] FSPActualParser.ConstantDefContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.indexRanges"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndexRanges([NotNull] FSPActualParser.IndexRangesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.indexRanges"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndexRanges([NotNull] FSPActualParser.IndexRangesContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.fsp_description"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFsp_description([NotNull] FSPActualParser.Fsp_descriptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.fsp_description"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFsp_description([NotNull] FSPActualParser.Fsp_descriptionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.processRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProcessRef([NotNull] FSPActualParser.ProcessRefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.processRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProcessRef([NotNull] FSPActualParser.ProcessRefContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.actionRange"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActionRange([NotNull] FSPActualParser.ActionRangeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.actionRange"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActionRange([NotNull] FSPActualParser.ActionRangeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.shiftExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShiftExpr([NotNull] FSPActualParser.ShiftExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.shiftExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShiftExpr([NotNull] FSPActualParser.ShiftExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.multiplicativeExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiplicativeExpr([NotNull] FSPActualParser.MultiplicativeExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.multiplicativeExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiplicativeExpr([NotNull] FSPActualParser.MultiplicativeExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.additiveExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdditiveExpr([NotNull] FSPActualParser.AdditiveExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.additiveExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdditiveExpr([NotNull] FSPActualParser.AdditiveExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.argumentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgumentList([NotNull] FSPActualParser.ArgumentListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.argumentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgumentList([NotNull] FSPActualParser.ArgumentListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.actionLabelsTail"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActionLabelsTail([NotNull] FSPActualParser.ActionLabelsTailContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.actionLabelsTail"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActionLabelsTail([NotNull] FSPActualParser.ActionLabelsTailContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.unaryExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryExpr([NotNull] FSPActualParser.UnaryExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.unaryExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryExpr([NotNull] FSPActualParser.UnaryExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.relationalExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelationalExpr([NotNull] FSPActualParser.RelationalExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.relationalExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelationalExpr([NotNull] FSPActualParser.RelationalExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.progressDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgressDef([NotNull] FSPActualParser.ProgressDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.progressDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgressDef([NotNull] FSPActualParser.ProgressDefContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.actionLabels"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActionLabels([NotNull] FSPActualParser.ActionLabelsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.actionLabels"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActionLabels([NotNull] FSPActualParser.ActionLabelsContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.bitExclOrExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBitExclOrExpr([NotNull] FSPActualParser.BitExclOrExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.bitExclOrExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBitExclOrExpr([NotNull] FSPActualParser.BitExclOrExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.processDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProcessDef([NotNull] FSPActualParser.ProcessDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.processDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProcessDef([NotNull] FSPActualParser.ProcessDefContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace LTSASharp.Parsing
