//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.2.2-SNAPSHOT
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from E:\Projects\C#\LTSASharp\LTSASharp\Parsing\FSPActual.g4 by ANTLR 4.2.2-SNAPSHOT

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

namespace LTSASharp.Parsing {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="FSPActualParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.2.2-SNAPSHOT")]
public interface IFSPActualListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.relabelDefs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelabelDefs([NotNull] FSPActualParser.RelabelDefsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.relabelDefs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelabelDefs([NotNull] FSPActualParser.RelabelDefsContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] FSPActualParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] FSPActualParser.ExpressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.compositeDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompositeDef([NotNull] FSPActualParser.CompositeDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.compositeDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompositeDef([NotNull] FSPActualParser.CompositeDefContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.actionPrefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActionPrefix([NotNull] FSPActualParser.ActionPrefixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.actionPrefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActionPrefix([NotNull] FSPActualParser.ActionPrefixContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.bitOrExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBitOrExpr([NotNull] FSPActualParser.BitOrExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.bitOrExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBitOrExpr([NotNull] FSPActualParser.BitOrExprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.ranges"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRanges([NotNull] FSPActualParser.RangesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.ranges"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRanges([NotNull] FSPActualParser.RangesContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.fltl_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFltl_or([NotNull] FSPActualParser.Fltl_orContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.fltl_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFltl_or([NotNull] FSPActualParser.Fltl_orContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.localProcess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocalProcess([NotNull] FSPActualParser.LocalProcessContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.localProcess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocalProcess([NotNull] FSPActualParser.LocalProcessContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.seqProcessList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSeqProcessList([NotNull] FSPActualParser.SeqProcessListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.seqProcessList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSeqProcessList([NotNull] FSPActualParser.SeqProcessListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.priority"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPriority([NotNull] FSPActualParser.PriorityContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.priority"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPriority([NotNull] FSPActualParser.PriorityContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.sequentialComposition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSequentialComposition([NotNull] FSPActualParser.SequentialCompositionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.sequentialComposition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSequentialComposition([NotNull] FSPActualParser.SequentialCompositionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterList([NotNull] FSPActualParser.ParameterListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterList([NotNull] FSPActualParser.ParameterListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.rangeDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRangeDef([NotNull] FSPActualParser.RangeDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.rangeDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRangeDef([NotNull] FSPActualParser.RangeDefContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.fltl_base"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFltl_base([NotNull] FSPActualParser.Fltl_baseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.fltl_base"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFltl_base([NotNull] FSPActualParser.Fltl_baseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.menuDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMenuDef([NotNull] FSPActualParser.MenuDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.menuDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMenuDef([NotNull] FSPActualParser.MenuDefContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.equalityExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqualityExpr([NotNull] FSPActualParser.EqualityExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.equalityExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqualityExpr([NotNull] FSPActualParser.EqualityExprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.prefixLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrefixLabel([NotNull] FSPActualParser.PrefixLabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.prefixLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrefixLabel([NotNull] FSPActualParser.PrefixLabelContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.actionLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActionLabel([NotNull] FSPActualParser.ActionLabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.actionLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActionLabel([NotNull] FSPActualParser.ActionLabelContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.assertDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssertDef([NotNull] FSPActualParser.AssertDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.assertDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssertDef([NotNull] FSPActualParser.AssertDefContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgument([NotNull] FSPActualParser.ArgumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgument([NotNull] FSPActualParser.ArgumentContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.propertyDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropertyDef([NotNull] FSPActualParser.PropertyDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.propertyDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropertyDef([NotNull] FSPActualParser.PropertyDefContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.fltl_binary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFltl_binary([NotNull] FSPActualParser.Fltl_binaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.fltl_binary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFltl_binary([NotNull] FSPActualParser.Fltl_binaryContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.bitAndExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBitAndExpr([NotNull] FSPActualParser.BitAndExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.bitAndExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBitAndExpr([NotNull] FSPActualParser.BitAndExprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.setDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetDef([NotNull] FSPActualParser.SetDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.setDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetDef([NotNull] FSPActualParser.SetDefContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.actionLabelTail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActionLabelTail([NotNull] FSPActualParser.ActionLabelTailContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.actionLabelTail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActionLabelTail([NotNull] FSPActualParser.ActionLabelTailContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.fltl_and"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFltl_and([NotNull] FSPActualParser.Fltl_andContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.fltl_and"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFltl_and([NotNull] FSPActualParser.Fltl_andContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.orExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrExpr([NotNull] FSPActualParser.OrExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.orExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrExpr([NotNull] FSPActualParser.OrExprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.baseLocalProcess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBaseLocalProcess([NotNull] FSPActualParser.BaseLocalProcessContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.baseLocalProcess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBaseLocalProcess([NotNull] FSPActualParser.BaseLocalProcessContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.alphabetExtension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAlphabetExtension([NotNull] FSPActualParser.AlphabetExtensionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.alphabetExtension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAlphabetExtension([NotNull] FSPActualParser.AlphabetExtensionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.hiding"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHiding([NotNull] FSPActualParser.HidingContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.hiding"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHiding([NotNull] FSPActualParser.HidingContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.relabelDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelabelDef([NotNull] FSPActualParser.RelabelDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.relabelDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelabelDef([NotNull] FSPActualParser.RelabelDefContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.indices"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndices([NotNull] FSPActualParser.IndicesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.indices"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndices([NotNull] FSPActualParser.IndicesContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.parallelComposition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParallelComposition([NotNull] FSPActualParser.ParallelCompositionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.parallelComposition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParallelComposition([NotNull] FSPActualParser.ParallelCompositionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.simpleExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleExpression([NotNull] FSPActualParser.SimpleExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.simpleExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleExpression([NotNull] FSPActualParser.SimpleExpressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.localProcessDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocalProcessDef([NotNull] FSPActualParser.LocalProcessDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.localProcessDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocalProcessDef([NotNull] FSPActualParser.LocalProcessDefContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.andExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAndExpr([NotNull] FSPActualParser.AndExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.andExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAndExpr([NotNull] FSPActualParser.AndExprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRange([NotNull] FSPActualParser.RangeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRange([NotNull] FSPActualParser.RangeContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.choice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChoice([NotNull] FSPActualParser.ChoiceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.choice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChoice([NotNull] FSPActualParser.ChoiceContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParam([NotNull] FSPActualParser.ParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParam([NotNull] FSPActualParser.ParamContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSet([NotNull] FSPActualParser.SetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSet([NotNull] FSPActualParser.SetContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.relabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelabel([NotNull] FSPActualParser.RelabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.relabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelabel([NotNull] FSPActualParser.RelabelContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.fsp_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFsp_definition([NotNull] FSPActualParser.Fsp_definitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.fsp_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFsp_definition([NotNull] FSPActualParser.Fsp_definitionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.setElements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetElements([NotNull] FSPActualParser.SetElementsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.setElements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetElements([NotNull] FSPActualParser.SetElementsContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.initially"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitially([NotNull] FSPActualParser.InitiallyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.initially"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitially([NotNull] FSPActualParser.InitiallyContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.localProcessDefs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocalProcessDefs([NotNull] FSPActualParser.LocalProcessDefsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.localProcessDefs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocalProcessDefs([NotNull] FSPActualParser.LocalProcessDefsContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.fltl_unary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFltl_unary([NotNull] FSPActualParser.Fltl_unaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.fltl_unary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFltl_unary([NotNull] FSPActualParser.Fltl_unaryContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.compositeBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompositeBody([NotNull] FSPActualParser.CompositeBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.compositeBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompositeBody([NotNull] FSPActualParser.CompositeBodyContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter([NotNull] FSPActualParser.ParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter([NotNull] FSPActualParser.ParameterContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.guard"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGuard([NotNull] FSPActualParser.GuardContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.guard"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGuard([NotNull] FSPActualParser.GuardContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.baseExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBaseExpr([NotNull] FSPActualParser.BaseExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.baseExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBaseExpr([NotNull] FSPActualParser.BaseExprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.fluentDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFluentDef([NotNull] FSPActualParser.FluentDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.fluentDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFluentDef([NotNull] FSPActualParser.FluentDefContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.processBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcessBody([NotNull] FSPActualParser.ProcessBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.processBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcessBody([NotNull] FSPActualParser.ProcessBodyContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.constantDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstantDef([NotNull] FSPActualParser.ConstantDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.constantDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstantDef([NotNull] FSPActualParser.ConstantDefContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.indexRanges"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndexRanges([NotNull] FSPActualParser.IndexRangesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.indexRanges"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndexRanges([NotNull] FSPActualParser.IndexRangesContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.fsp_description"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFsp_description([NotNull] FSPActualParser.Fsp_descriptionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.fsp_description"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFsp_description([NotNull] FSPActualParser.Fsp_descriptionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.processRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcessRef([NotNull] FSPActualParser.ProcessRefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.processRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcessRef([NotNull] FSPActualParser.ProcessRefContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.actionRange"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActionRange([NotNull] FSPActualParser.ActionRangeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.actionRange"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActionRange([NotNull] FSPActualParser.ActionRangeContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.shiftExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShiftExpr([NotNull] FSPActualParser.ShiftExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.shiftExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShiftExpr([NotNull] FSPActualParser.ShiftExprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.multiplicativeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicativeExpr([NotNull] FSPActualParser.MultiplicativeExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.multiplicativeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicativeExpr([NotNull] FSPActualParser.MultiplicativeExprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.additiveExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditiveExpr([NotNull] FSPActualParser.AdditiveExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.additiveExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditiveExpr([NotNull] FSPActualParser.AdditiveExprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgumentList([NotNull] FSPActualParser.ArgumentListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgumentList([NotNull] FSPActualParser.ArgumentListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.actionLabelsTail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActionLabelsTail([NotNull] FSPActualParser.ActionLabelsTailContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.actionLabelsTail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActionLabelsTail([NotNull] FSPActualParser.ActionLabelsTailContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.unaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryExpr([NotNull] FSPActualParser.UnaryExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.unaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryExpr([NotNull] FSPActualParser.UnaryExprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.relationalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationalExpr([NotNull] FSPActualParser.RelationalExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.relationalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationalExpr([NotNull] FSPActualParser.RelationalExprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.progressDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgressDef([NotNull] FSPActualParser.ProgressDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.progressDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgressDef([NotNull] FSPActualParser.ProgressDefContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.actionLabels"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActionLabels([NotNull] FSPActualParser.ActionLabelsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.actionLabels"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActionLabels([NotNull] FSPActualParser.ActionLabelsContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.bitExclOrExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBitExclOrExpr([NotNull] FSPActualParser.BitExclOrExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.bitExclOrExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBitExclOrExpr([NotNull] FSPActualParser.BitExclOrExprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FSPActualParser.processDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcessDef([NotNull] FSPActualParser.ProcessDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSPActualParser.processDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcessDef([NotNull] FSPActualParser.ProcessDefContext context);
}
} // namespace LTSASharp.Parsing
